import type { 
  Agent, 
  Lead, 
  Conversation, 
  Message, 
  Appointment, 
  Listing, 
  CreditAccount, 
  CreditLedgerEntry,
  Notification,
  Task,
  AgentMetrics,
  LeadActivity,
} from '@/types/agents';

export const mockAgent: Agent = {
  id: 'agent-1',
  email: 'carlos.mendez@realty.com',
  phone: '+52 55 1234 5678',
  firstName: 'Carlos',
  lastName: 'Mendez',
  avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
  licenseNumber: 'RE-2024-001234',
  licenseState: 'CDMX',
  bio: 'Especialista en propiedades residenciales en la zona centro.',
  specialties: ['residential_buy', 'residential_sell', 'first_time_buyer'],
  zones: [
    { id: 'zone-1', name: 'Condesa', type: 'neighborhood' },
    { id: 'zone-2', name: 'Roma Norte', type: 'neighborhood' },
    { id: 'zone-3', name: 'Polanco', type: 'neighborhood' },
  ],
  languages: ['Español', 'English'],
  teamId: 'team-1',
  role: 'owner',
  status: 'active',
  profileCompletion: 85,
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2026-01-28'),
};

export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    firstName: 'María',
    lastName: 'García',
    email: 'maria.garcia@email.com',
    phone: '+52 55 9876 5432',
    stage: 'engaged',
    score: 85,
    temperature: 'hot',
    assignedTo: 'agent-1',
    source: 'marketplace',
    interestedIn: 'buy',
    propertyType: 'apartment',
    budgetMin: 3000000,
    budgetMax: 5000000,
    preferredZones: ['Condesa', 'Roma Norte'],
    notes: 'Busca departamento de 2 recámaras con estacionamiento',
    lastContactedAt: new Date('2026-01-28T10:30:00'),
    lastActivityAt: new Date('2026-01-28T14:00:00'),
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'lead-2',
    firstName: 'Roberto',
    lastName: 'Hernández',
    email: 'roberto.h@email.com',
    phone: '+52 55 5555 1234',
    stage: 'new',
    score: 65,
    temperature: 'warm',
    assignedTo: 'agent-1',
    source: 'referral',
    interestedIn: 'buy',
    propertyType: 'house',
    budgetMin: 8000000,
    budgetMax: 12000000,
    preferredZones: ['Polanco'],
    createdAt: new Date('2026-01-27'),
    updatedAt: new Date('2026-01-27'),
  },
  {
    id: 'lead-3',
    firstName: 'Ana',
    lastName: 'López',
    email: 'ana.lopez@email.com',
    stage: 'appointment_set',
    score: 90,
    temperature: 'hot',
    assignedTo: 'agent-1',
    source: 'marketplace',
    interestedIn: 'rent',
    propertyType: 'apartment',
    budgetMin: 15000,
    budgetMax: 25000,
    lastContactedAt: new Date('2026-01-27'),
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'lead-4',
    firstName: 'Pedro',
    lastName: 'Sánchez',
    stage: 'contacted',
    score: 50,
    temperature: 'cold',
    assignedTo: 'agent-1',
    source: 'website',
    interestedIn: 'sell',
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-01-26'),
  },
  {
    id: 'lead-5',
    firstName: 'Laura',
    lastName: 'Martínez',
    email: 'laura.m@email.com',
    phone: '+52 55 4444 3333',
    stage: 'met',
    score: 75,
    temperature: 'warm',
    assignedTo: 'agent-1',
    source: 'marketplace',
    interestedIn: 'buy',
    propertyType: 'condo',
    budgetMin: 4000000,
    budgetMax: 6000000,
    lastContactedAt: new Date('2026-01-26'),
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'lead-6',
    firstName: 'Jorge',
    lastName: 'Ramírez',
    stage: 'negotiating',
    score: 95,
    temperature: 'hot',
    assignedTo: 'agent-1',
    source: 'referral',
    interestedIn: 'buy',
    propertyType: 'house',
    budgetMin: 15000000,
    budgetMax: 20000000,
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-01-28'),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    leadId: 'lead-1',
    lead: mockLeads[0],
    lastMessage: {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'lead-1',
      senderType: 'lead',
      content: '¿Podemos agendar una visita para este fin de semana?',
      contentType: 'text',
      status: 'delivered',
      createdAt: new Date('2026-01-28T14:00:00'),
    },
    unreadCount: 1,
    status: 'active',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-28T14:00:00'),
  },
  {
    id: 'conv-2',
    leadId: 'lead-3',
    lead: mockLeads[2],
    lastMessage: {
      id: 'msg-2',
      conversationId: 'conv-2',
      senderId: 'agent-1',
      senderType: 'agent',
      content: 'Perfecto, te confirmo la cita para mañana a las 11am.',
      contentType: 'text',
      status: 'read',
      createdAt: new Date('2026-01-27T16:30:00'),
      readAt: new Date('2026-01-27T16:45:00'),
    },
    unreadCount: 0,
    status: 'active',
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-27T16:30:00'),
  },
  {
    id: 'conv-3',
    leadId: 'lead-5',
    lead: mockLeads[4],
    lastMessage: {
      id: 'msg-3',
      conversationId: 'conv-3',
      senderId: 'lead-5',
      senderType: 'lead',
      content: 'Me interesa mucho el departamento de la Roma. ¿Sigue disponible?',
      contentType: 'text',
      status: 'delivered',
      createdAt: new Date('2026-01-28T09:15:00'),
    },
    unreadCount: 1,
    status: 'active',
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-28T09:15:00'),
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'agent-1',
    senderType: 'agent',
    content: '¡Hola María! Gracias por tu interés. Tengo varias opciones que podrían interesarte.',
    contentType: 'text',
    status: 'read',
    createdAt: new Date('2026-01-20T10:00:00'),
    readAt: new Date('2026-01-20T10:05:00'),
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'lead-1',
    senderType: 'lead',
    content: '¡Hola Carlos! Me encantaría conocer más detalles.',
    contentType: 'text',
    status: 'read',
    createdAt: new Date('2026-01-20T11:30:00'),
    readAt: new Date('2026-01-20T11:35:00'),
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'agent-1',
    senderType: 'agent',
    content: 'Te comparto este departamento en la Condesa que cumple con lo que buscas: 2 recámaras, estacionamiento, y excelente ubicación.',
    contentType: 'text',
    status: 'read',
    createdAt: new Date('2026-01-28T10:30:00'),
    readAt: new Date('2026-01-28T10:45:00'),
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'lead-1',
    senderType: 'lead',
    content: '¿Podemos agendar una visita para este fin de semana?',
    contentType: 'text',
    status: 'delivered',
    createdAt: new Date('2026-01-28T14:00:00'),
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    leadId: 'lead-3',
    lead: mockLeads[2],
    agentId: 'agent-1',
    listingId: 'listing-2',
    type: 'showing',
    status: 'confirmed',
    scheduledAt: new Date('2026-01-29T11:00:00'),
    duration: 60,
    location: 'Av. Álvaro Obregón 145, Roma Norte',
    notes: 'La cliente prefiere ver el departamento por la mañana',
    createdAt: new Date('2026-01-27'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'apt-2',
    leadId: 'lead-1',
    lead: mockLeads[0],
    agentId: 'agent-1',
    listingId: 'listing-1',
    type: 'showing',
    status: 'pending',
    scheduledAt: new Date('2026-01-30T16:00:00'),
    duration: 45,
    location: 'Calle Tamaulipas 87, Condesa',
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'apt-3',
    leadId: 'lead-6',
    lead: mockLeads[5],
    agentId: 'agent-1',
    type: 'consultation',
    status: 'confirmed',
    scheduledAt: new Date('2026-01-31T10:00:00'),
    duration: 90,
    virtualLink: 'https://meet.example.com/abc123',
    notes: 'Reunión para discutir opciones de financiamiento',
    createdAt: new Date('2026-01-26'),
    updatedAt: new Date('2026-01-28'),
  },
];

export const mockListings: Listing[] = [
  {
    id: 'listing-1',
    agentId: 'agent-1',
    address: {
      street: 'Calle Tamaulipas 87',
      city: 'Ciudad de México',
      state: 'CDMX',
      zip: '06140',
      country: 'México',
    },
    propertyType: 'apartment',
    listingType: 'sale',
    price: 4500000,
    currency: 'MXN',
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 95,
    yearBuilt: 2020,
    amenities: ['Estacionamiento', 'Roof Garden', 'Gimnasio', 'Seguridad 24/7'],
    description: 'Hermoso departamento en la Condesa con acabados de lujo y excelente ubicación.',
    media: [
      { id: 'm1', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800', type: 'image', order: 1 },
      { id: 'm2', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800', type: 'image', order: 2 },
    ],
    status: 'active',
    verificationStatus: 'verified',
    viewCount: 245,
    saveCount: 18,
    inquiryCount: 5,
    listedAt: new Date('2026-01-10'),
    createdAt: new Date('2026-01-08'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'listing-2',
    agentId: 'agent-1',
    address: {
      street: 'Av. Álvaro Obregón 145',
      unit: 'PH-1',
      city: 'Ciudad de México',
      state: 'CDMX',
      zip: '06700',
      country: 'México',
    },
    propertyType: 'apartment',
    listingType: 'rent',
    price: 22000,
    currency: 'MXN',
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 65,
    yearBuilt: 2018,
    amenities: ['Amueblado', 'Terraza', 'Pet Friendly'],
    description: 'Penthouse moderno en Roma Norte, completamente amueblado y listo para habitar.',
    media: [
      { id: 'm3', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800', type: 'image', order: 1 },
    ],
    status: 'active',
    verificationStatus: 'verified',
    viewCount: 189,
    saveCount: 12,
    inquiryCount: 8,
    listedAt: new Date('2026-01-15'),
    createdAt: new Date('2026-01-14'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'listing-3',
    agentId: 'agent-1',
    address: {
      street: 'Campos Elíseos 200',
      city: 'Ciudad de México',
      state: 'CDMX',
      zip: '11560',
      country: 'México',
    },
    propertyType: 'house',
    listingType: 'sale',
    price: 18500000,
    currency: 'MXN',
    bedrooms: 4,
    bathrooms: 3.5,
    squareFeet: 320,
    yearBuilt: 2015,
    amenities: ['Jardín', 'Alberca', '3 Estacionamientos', 'Cuarto de Servicio'],
    description: 'Casa de lujo en Polanco con acabados premium y amplio jardín.',
    media: [
      { id: 'm4', url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800', type: 'image', order: 1 },
      { id: 'm5', url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800', type: 'image', order: 2 },
    ],
    status: 'active',
    verificationStatus: 'pending',
    viewCount: 67,
    saveCount: 4,
    inquiryCount: 2,
    listedAt: new Date('2026-01-25'),
    createdAt: new Date('2026-01-24'),
    updatedAt: new Date('2026-01-28'),
  },
  {
    id: 'listing-4',
    agentId: 'agent-1',
    address: {
      street: 'Calle Durango 250',
      city: 'Ciudad de México',
      state: 'CDMX',
      zip: '06700',
      country: 'México',
    },
    propertyType: 'apartment',
    listingType: 'sale',
    price: 3200000,
    currency: 'MXN',
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 55,
    amenities: ['Balcón', 'Excelente ubicación'],
    description: 'Departamento ideal para inversión o primera vivienda.',
    media: [],
    status: 'draft',
    verificationStatus: 'none',
    viewCount: 0,
    saveCount: 0,
    inquiryCount: 0,
    createdAt: new Date('2026-01-28'),
    updatedAt: new Date('2026-01-28'),
  },
];

export const mockCreditAccount: CreditAccount = {
  id: 'credit-1',
  ownerId: 'agent-1',
  ownerType: 'agent',
  balance: 150,
  currency: 'credits',
  lowBalanceThreshold: 20,
  dailyLimit: 50,
  rules: [
    { id: 'rule-1', action: 'lead_basic', cost: 2, isEnabled: true },
    { id: 'rule-2', action: 'lead_premium', cost: 5, isEnabled: true },
    { id: 'rule-3', action: 'boost_24h', cost: 10, isEnabled: true },
    { id: 'rule-4', action: 'boost_7d', cost: 50, isEnabled: false },
    { id: 'rule-5', action: 'featured_listing', cost: 100, isEnabled: false },
    { id: 'rule-6', action: 'verification_request', cost: 15, isEnabled: true },
  ],
  createdAt: new Date('2024-01-15'),
  updatedAt: new Date('2026-01-28'),
};

export const mockLedger: CreditLedgerEntry[] = [
  {
    id: 'ledger-1',
    accountId: 'credit-1',
    type: 'debit',
    amount: 5,
    balance: 150,
    description: 'Lead premium: María García',
    referenceType: 'lead',
    referenceId: 'lead-1',
    createdAt: new Date('2026-01-28T08:00:00'),
  },
  {
    id: 'ledger-2',
    accountId: 'credit-1',
    type: 'debit',
    amount: 10,
    balance: 155,
    description: 'Boost 24h: Depto Condesa',
    referenceType: 'listing',
    referenceId: 'listing-1',
    createdAt: new Date('2026-01-27T14:00:00'),
  },
  {
    id: 'ledger-3',
    accountId: 'credit-1',
    type: 'credit',
    amount: 100,
    balance: 165,
    description: 'Recarga de créditos',
    referenceType: 'recharge',
    createdAt: new Date('2026-01-25T10:00:00'),
  },
  {
    id: 'ledger-4',
    accountId: 'credit-1',
    type: 'debit',
    amount: 15,
    balance: 65,
    description: 'Solicitud de verificación: Casa Polanco',
    referenceType: 'listing',
    referenceId: 'listing-3',
    createdAt: new Date('2026-01-24T16:00:00'),
  },
  {
    id: 'ledger-5',
    accountId: 'credit-1',
    type: 'debit',
    amount: 2,
    balance: 80,
    description: 'Lead básico: Roberto Hernández',
    referenceType: 'lead',
    referenceId: 'lead-2',
    createdAt: new Date('2026-01-23T09:00:00'),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    recipientId: 'agent-1',
    type: 'new_message',
    title: 'Nuevo mensaje',
    body: 'María García te envió un mensaje',
    actionUrl: '/agents/inbox/conv-1',
    read: false,
    createdAt: new Date('2026-01-28T14:00:00'),
  },
  {
    id: 'notif-2',
    recipientId: 'agent-1',
    type: 'appointment_confirmed',
    title: 'Cita confirmada',
    body: 'Ana López confirmó la visita de mañana 11am',
    actionUrl: '/agents/calendar',
    read: false,
    createdAt: new Date('2026-01-28T09:30:00'),
  },
  {
    id: 'notif-3',
    recipientId: 'agent-1',
    type: 'listing_activity',
    title: 'Tu listing está trending 🔥',
    body: 'Depto Condesa tuvo 45 views hoy (+180%)',
    actionUrl: '/agents/listings/listing-1',
    read: true,
    createdAt: new Date('2026-01-27T18:00:00'),
  },
  {
    id: 'notif-4',
    recipientId: 'agent-1',
    type: 'new_lead',
    title: 'Nuevo lead asignado',
    body: 'Roberto Hernández está interesado en comprar',
    actionUrl: '/agents/leads/lead-2',
    read: true,
    createdAt: new Date('2026-01-27T08:00:00'),
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    agentId: 'agent-1',
    leadId: 'lead-1',
    title: 'Enviar opciones de departamentos a María',
    priority: 'high',
    status: 'pending',
    dueAt: new Date('2026-01-29'),
    createdAt: new Date('2026-01-28'),
  },
  {
    id: 'task-2',
    agentId: 'agent-1',
    leadId: 'lead-2',
    title: 'Llamar a Roberto para seguimiento',
    priority: 'medium',
    status: 'pending',
    dueAt: new Date('2026-01-29'),
    createdAt: new Date('2026-01-27'),
  },
  {
    id: 'task-3',
    agentId: 'agent-1',
    listingId: 'listing-4',
    title: 'Completar fotos del listing Durango',
    priority: 'low',
    status: 'pending',
    dueAt: new Date('2026-01-30'),
    createdAt: new Date('2026-01-28'),
  },
];

export const mockMetrics: AgentMetrics = {
  responseTimeAvg: 45,
  responseRate: 94,
  leadsActive: 6,
  appointmentsThisWeek: 3,
  noShowRate: 5,
  conversionToAppointment: 35,
  closedWonRate: 12,
  healthScore: 78,
};

export const mockLeadActivities: LeadActivity[] = [
  {
    id: 'act-1',
    leadId: 'lead-1',
    type: 'message_received',
    description: 'Nuevo mensaje de María García',
    metadata: { channel: 'chat' },
    createdBy: 'lead-1',
    createdAt: new Date('2026-01-28T14:00:00'),
  },
  {
    id: 'act-2',
    leadId: 'lead-1',
    type: 'appointment_scheduled',
    description: 'Cita agendada para sábado 11:00',
    metadata: { appointmentId: 'apt-2' },
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-28T14:05:00'),
  },
  {
    id: 'act-3',
    leadId: 'lead-2',
    type: 'call_made',
    description: 'Llamada de seguimiento realizada',
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-28T12:00:00'),
  },
  {
    id: 'act-4',
    leadId: 'lead-2',
    type: 'note_added',
    description: 'Prefiere citas después de las 6pm; vive en Querétaro y viaja a CDMX.',
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-28T12:10:00'),
  },
  {
    id: 'act-5',
    leadId: 'lead-3',
    type: 'stage_change',
    description: 'Lead movido a Cita Agendada',
    metadata: { from: 'engaged', to: 'appointment_set' },
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-27T10:00:00'),
  },
  {
    id: 'act-6',
    leadId: 'lead-5',
    type: 'appointment_completed',
    description: 'Tour completado, interesada en oferta',
    metadata: { appointmentId: 'apt-3' },
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-26T11:30:00'),
  },
  {
    id: 'act-7',
    leadId: 'lead-6',
    type: 'message_sent',
    description: 'Se envió brochure y términos de oferta',
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-25T09:00:00'),
  },
  {
    id: 'act-8',
    leadId: 'lead-4',
    type: 'assignment_changed',
    description: 'Asignado a Carlos Mendez',
    createdBy: 'agent-1',
    createdAt: new Date('2026-01-24T08:30:00'),
  },
];
